[package]
name = "cane"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
macroquad = { version = "0.4.14", optional = true }

[features]
macroquad = ["dep:macroquad"]

