[package]
name = "cane"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Window", "Document", "Node", "Element", "HtmlElement", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
